### PR TITLE
Include resolve-uri source directly in trace-mapping project

### PR DESCRIPTION
**Pull request by benmccann**
Similar to https://github.com/jridgewell/sourcemaps/pull/1, we could probably use this source file directly and eliminate the need for an extra project

### CODE REVIEW

**Comment by jridgewell** [comment]
This one needs to stay external. There's a stagnant PR to add `applySourcemap` to `gen-mapping` which needs it, and an issue in remapping to fix relative paths after merging maps.

Part of my reason to move to a monorepo was to finalize these cross-repo tasks.

**Comment by benmccann** [comment]
Sounds good. Does it need to stay external just temporarily until those PRs get merged or were you saying the plan is for multiple packages to eventually use it?

Another thing I wonder about is just putting everything in one package like `@jrdigewell/sourcemaps` with separate entry points for each. The source for each is relatively small and bundlers can tree shake out anything that's unused

**Comment by jridgewell** [comment]
Multiple packages would eventually use it.

> Another thing I wonder about is just putting everything in one package like `@jrdigewell/sourcemaps` with separate entry points for each. The source for each is relatively small and bundlers can tree shake out anything that's unused

I hadn't considered that. It's possible that we could do that while still individually publishing the current modules.

**Comment by benmccann** [comment]
I think if they were going to be combined into a single package then that should probably be the only way they were distributed because otherwise you can end up with the combined and separated versions both in your dependency tree and they won't deduplicate

**Pull request closed without merging**
